### ISSUE TITLE
Notify on specific branch

### ISSUE THREAD

**Issue by eneim** [wantedly/step-pretty-slack-notify#13]
特定なブランチだけでのビルド結果を通知できると嬉しいです。

run.rb の中にgit_branchを指定する場所があるから、そこで何とか工夫できるかなと考えています。
自分がrubyうまくないので、PRなど出来ず、任せます。

よろしくお願いします。

**Comment by spesnova** [comment]
要望ありがとうございます :exclamation: :smiley:
今週は時間取れないので来週対応しようと思います〜

Thank you for your request :)
I'll update it next week.

**Comment by spesnova** [comment]
@eneim かなり遅くなってしまいましたが、対応してみました :bulb:
