### ISSUE TITLE
add ability to only deploy on failures

### ISSUE THREAD

**Issue by nhumrich** [wantedly/step-pretty-slack-notify#17]
the standard wercker slack notifier has a flag `notify_on` that allows you to specify whether to notify on failures only, for example:

    after-steps:
      - slack-notifier:
        url: $SLACK_URL
        channel: $CHANNEL
        notify_on: "failed"

It would be nice to have this feature on pretty-slack-notify

**Comment by koudaiii** [comment]
Thank you for feed back :+1:
I will try :)
 Please wait a little.

**Comment by koudaiii** [comment]
Released  0.2.11
* https://app.wercker.com/#applications/53e31d00631d554c4802d374/tab/details

Please give it a try :)
Thank you.
