### ISSUE TITLE
Add ability to notify user

### ISSUE THREAD

**Issue by RomanTsegelskyi** [wantedly/step-pretty-slack-notify#20]
Would it be possible to add support for @user to send a DM to a specific user?

**Comment by awakia** [comment]
Hi @RomanTsegelskyi 
I think you can do it by yourself.

See [this document](https://api.slack.com/docs/formatting) and do something like

```
<@U024BE7LH|bob>
```

The user id can be found at https://api.slack.com/methods/users.list/test when you click "Test Method" button.

Good luck :+1:
