### ISSUE TITLE
Add ability to define messages

### ISSUE THREAD

**Issue by berstend** [wantedly/step-pretty-slack-notify#27]
Great job with this!

It'd be great to be able to (optionally) define messages for passed / failed {builds,deploys} to use this step in more places and to add more $debug information.

Similar to this one: https://github.com/sherzberg/wercker-step-slack-notify#optional

**Comment by awakia** [comment]
@berstend Thank you for the idea.

I think this function is **nice to have** feature. But to implement many **nice to have** feature usually reduce usability. I want step-pretty-slack-notify to keep simple. So, can you describe why you need to customize messages? 

p.s. Pull Request is greatly appreciated for such features :smile_cat:

**Comment by zeisss** [comment]
I was looking for this too. My use case is to provide an URL to the deployed site in slack, so my team mates can just click the link when seeing the deployment happened in Slack.

**Comment by awakia** [comment]
@spesnova @dtan4 This function is requested multiple users. If you have time, can you consider to add the functionality?

**Comment by awakia** [comment]
@spesnova @dtan4 Thanks! great work!!
