### ISSUE TITLE
How to setup wercker.yml for none Ruby boxes?

### ISSUE THREAD

**Issue by hyzhak** [wantedly/step-pretty-slack-notify#28]
Hello guys! I'm developing node.js application and using node.js box. And would like to connect this step to push notification to slack. But got such error:

![](https://pbs.twimg.com/media/CYt5beSW8AIozXi.png)

```
You need to use a box that installed ruby
```

**Comment by hyzhak** [comment]
oh, it was very easy: http://devcenter.wercker.com/docs/steps/install-packages.html

just define:
```yaml
- install-packages:
        packages: ruby
```

**Comment by koudaiii** [comment]
Thank you for the valuable information :+1: 
I add the information in README :)

**Comment by danielmahon** [comment]
FYI, this is NOT in the README, I had a hard time figuring it out for a `node` box

**Comment by koudaiii** [comment]
Thank you for message.
Update README :shipit: 
https://github.com/wantedly/step-pretty-slack-notify/pull/29
